---
- name: Let's start the work
  hosts: server
  user: nidhi
  become: yes
  tasks:
          - name: Let's install httpd service
            yum:
                    name: httpd
                    state: present

          - pause: seconds=10

          - name: Let's start the httpd service
            service:
                    name: httpd
                    state: started

          - pause: seconds=10

          - name: Let's copy the content
            copy:
                    src: /home/ec2-user/learning_website/
                    dest: /var/www/html/

          -  pause: seconds=60

          - name: Delete the content of web services
            file:
                    path: /var/www/html/
                    state: absent

          - pause: seconds=10
          
          - name: Let's stop the httpd service
            service:
                    name: httpd
                    state: stopped

          - pause: seconds=10

          - name: Let's uninstall httpd service
            yum:
                    name: httpd
                    state: absent

          - pause: seconds=10
                  
